// code for client
export const HTTP_SWITCHING_PROTOKOL = 101;

export const HTTP_STATUS_OK = 200;
export const HTTP_STATUS_CREATED = 201;
export const HTTP_STATUS_NO_CONTENT = 204;
export const HTTP_STATUS_RESET_CONTENT = 205;

export const HTTP_NOT_MODIFIED = 304;

export const HTTP_STATUS_BAD_REQUEST = 400;
export const HTTP_STATUS_FORBIDDEN = 403;
export const HTTP_STATUS_HOST_UNAVAILABLE = 434;
export const HTTP_STATUS_CLIENT_CLOSED_REQUEST = 499;

export const HTTP_STATUS_SERVER_ERROR = 500;
export const HTTP_STATUS_SERVICE_UNAVAILABLE = 503;
export const HTTP_UNKNOWN_ERROR = 520;
